language: node_js
install: 
- "npm install -g npm"
- "npm install"
before_script: "./node_modules/.bin/grunt compile"
script: "./node_modules/.bin/grunt test"
node_js:
  - "0.8"
  - "0.10"
cache:
  directories:
    - node_modules
